config/routes.rb
Rails.application.routes.draw do

  devise_for :autors
  get 'home/index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
  scope module: 'autors' do
    resources :posts do
      resources :elementos
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/autor.rb
class Autor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/elemento.rb
class Elemento < ApplicationRecord
  belongs_to :post
  has_rich_text :content
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :autor
  has_many :elementos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/autors/elementos_controller.rb
module Autors
    class ElementosController < AutorsController
      before_action :set_post
      before_action :set_elemento, only: %i[update destroy ]

            # POST /elementos
      def create
        @elemento = @post.elementos.build(elemento_params)

        if @elemento.save
          notice = nil
        else
         notice = @elemento.errors.full_messages.join(". ") << "."
       end
         redirect_to edit_post_path(@post), notice: notice
      end

      # PATCH/PUT /elementos/1
      def update
        if @elemento.update(elemento_params)
          redirect_to edit_post_path(@elemento.post), notice: "El elemento se actualizó con éxito."
        end
      end

      # DELETE /elementos/1
      def destroy
        @elemento.destroy
        redirect_to elementos_url, notice: "El elemento fue eliminado con éxito."
      end

      private

      def set_post
        @post = current_autor.posts.find(params[:post_id])
      end

        # Use callbacks to share common setup or constraints between actions.
        def set_elemento
          @elemento = @post.elementos.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def elemento_params
          params.require(:elemento).permit(:elemento_tipo, :content)
        end
    end
end

app/controllers/autors/posts_controller.rb
module Autors
      class PostsController < AutorsController
      before_action :set_post, only: %i[ show edit update destroy ]

      # GET /posts
      def index
        @posts = current_autor.posts
      end

      # GET /posts/1
      def show
      end

      # GET /posts/new
      def new
        @post = current_autor.posts.build
      end

      # GET /posts/1/edit
      def edit
        @content = @post.elementos.build(elemento_tipo: "content")
      end

      # POST /posts
      def create
        @post = current_autor.posts.build(post_params)

        if @post.save
          redirect_to @post, notice: "La publicación se creó con éxito."
        else
          render :new, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /posts/1
      def update
        if @post.update(post_params)
          redirect_to @post, notice: "La publicación se actualizó con éxito."
        else
          render :edit, status: :unprocessable_entity
        end
      end

      # DELETE /posts/1
      def destroy
        @post.destroy
        redirect_to posts_url, notice: "La publicación fue Eliminada con éxito."
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_post
          @post = current_autor.posts.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def post_params
          params.require(:post).permit(:titulo, :titulo_descripcion)
        end
    end
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
  before_action :authenticate_autor!

  layout 'autors'
end 

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elementos_helper.rb
module ElementosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/autors/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> Prohibido guardar este post:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :Título %>
    <%= form.text_field :titulo, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :Descripción %>
    <%= form.text_area :titulo_descripcion, class: 'form-control'  %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/autors/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Titulo:</strong>
    <%= post.titulo %>
  </p>

  <p>
    <strong>Titulo descripcion:</strong>
    <%= post.titulo_descripcion %>
  </p>

  <p>
    <strong>Publicado:</strong>
    <%= post.publicado %>
  </p>

  <p>
    <strong>Publicado el:</strong>
    <%= post.publicado_el %>
  </p>

  <p>
    <strong>Autor:</strong>
    <%= post.autor_id %>
  </p>

</div>

app/views/autors/posts/edit.html.erb
<div class="row">
  <div class="col-md-3">
    <%= link_to "Regresar a los Posts", posts_path, class: "btn btn-secondary mb-3"%>
    <div class="card">
      <div class="card-body">
          <h4 class="card-title">Editar Post</h4>
          <%= render "form", post: @post %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <div class="mb-3">
      <%= form_with(model: [@post, @content]) do |form|%>
           <%= form.hidden_field :elemento_tipo, value: "content"%>
          <%= form.submit "Agregar Contenido", class: "btn btn-primary" %>
      <% end %>
    </div>


      <% @post.elementos.each do |elemento|%>
      <% if elemento.persisted? %>
            <%= form_with(model: [@post, elemento]) do |form|%>
                 <%= form.rich_text_area :content%>

                   <%= form.submit "Guardar", class: "btn btn-primary" %>
                

            <% end %>
      <%end %>
      <%end %>

  </div>
</div>

app/views/autors/posts/index.html.erb
<h4 class="d-flex justify-content-between mb-4">
  <span>Posts</span>
  <%= link_to "Nuevo Post", new_post_path, class: "btn btn-primary" %>
</h4>
<div id="posts">

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descripción</th>
      <th>Publicado</th>
      <th>Publicado el</th>
      <th>Autor</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.titulo %></td>
        <td><%= post.titulo_descripcion %></td>
        <td><%= post.publicado %></td>
        <td><%= post.publicado_el %></td>
        <td><%= post.autor_id %></td>
        <td><%= link_to "editar",edit_post_path(post),class: "btn btn-warning" %></td>
        <td><%= button_to "Eliminar",post,class:"btn btn-danger",confirm: "Estas seguro que quieres eliminar el Post?", method: :delete %></td>

      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="border-top" style="margin-top: 25px;margin-bottom: 25px;"></div>
<h4 class="d-flex justify-content-between mb-4">
  <span>Posts</span>
  <%= link_to "Nuevo Post", new_post_path, class: "btn btn-primary" %>
</h4>

  <% @posts.each do |post| %>
    <%= link_to edit_post_path(post), class:"text-decoration-none" do %>
      <div class="card">
        <div class="carf-body">
          <h5 class="card-title text-dark"><%= post.titulo%></h5>
          <p class="text-secondary"><%= post.titulo_descripcion%></p>
        </div>
      </div>
      <br>
    <%end%>
  <%end %>

app/views/autors/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Regresar a los Posts", posts_path %>
</div>

app/views/autors/posts/show.html.erb
<%= render @post %>

<div>
  <%= link_to "Editar", edit_post_path(@post) %> |
  <%= link_to "Regresar", posts_path %>

  <%= button_to "Eliminar", @post, method: :delete %>
</div>

app/views/home/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top" >
    <div class="col-md-4 d-flex align-items-center">
      <span class="text-muted">© 2022 Anuar Rodríguez, FullStack</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <%= link_to image_tag("https://dl.dropbox.com/s/wxehj6x8lfg6mdq/Whatsapp_icon.png?dl=0"), "https://wa.me/+529831208403",target: "_blank", style:"cursor: pointer; margin-right: 15px; width: 25px;" %>
      <%= link_to image_tag("https://dl.dropbox.com/s/27csxwvcjx29vht/github.png?dl=0"), "https://anuarxd.github.io",target: "_blank", style:"cursor: pointer; margin-right: 15px; width: 25px;" %>
      <%= link_to image_tag("https://dl.dropbox.com/s/02372t86016cina/Twitter_icon.png?dl=00"), "https://twitter.com/anuarxD", target: "_blank", style:"cursor: pointer; margin-right: 15px; width: 25px;" %>
      <%= link_to image_tag("https://dl.dropbox.com/s/c5liars6yt5rn8g/linkedin_icon.png?dl=0"), "https://www.linkedin.com/in/anuar-rodriguez",target: "_blank", style:"cursor: pointer; margin-right: 15px; width: 25px;" %>
      <%= link_to image_tag("https://dl.dropbox.com/s/x71y8ch1fdaggd1/Instagram_icon.png?dl=0"), "https://www.instagram.com/anuar.rodriguez.88/",target: "_blank", style:"cursor: pointer; margin-right: 15px; width: 25px;" %>
    </ul>
  </footer>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to image_tag("Logo1.png", style: 'width:65%;'), root_path, class:"navbar-brand" %>

     <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Acerca de Nosotros', home_about_path , class:"nav-link" %>
        </li>
        <li>
          <%= link_to 'BLOG', posts_path , class:"nav-link" %>
        </li>
      </ul>


      <div class="dropdown" style="margin-right: 20px">

          <% if autor_signed_in? %>
          <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
            Sesión Iniciada
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li>
              <%= link_to 'Editar Perfil', edit_autor_registration_path ,  class:"dropdown-item"%>
            </li>
            <li>
              <%= button_to 'Cerrar Sesión', destroy_autor_session_path, method: :delete,  class:"dropdown-item" %>
            </li>
          <% else %>
          <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
            Ingresar
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <li>
                <%= link_to 'Registrarse ', new_autor_registration_path ,  class:"dropdown-item" %>
              </li>
              <li>
                <%= link_to 'Iniciar Sesión', autor_session_path ,  class:"dropdown-item" %>
              </li>
          <% end %>
        </ul>
      </div>



  <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>

    </form>

    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="container text-center" >
  <h1>Acerca de Nosotros...</h1>
  <%= image_tag("Varias/const.gif") %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%= notice %> </strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <title>BlogFull</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>
  <body>
    <body>
      <%= render 'home/header'%>
  <div class="container" style="margin-top: 15px">
    <br>
    <% if notice %>
      <%= render 'layouts/alerts'%>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'home/footer'%>
  <!-- Optional JavaScript; choose one of the two! -->
  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <!-- Option 2: Separate Popper and Bootstrap JS -->

</body>
</html>

app/views/layouts/autors.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <title>BlogFull</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_importmap_tags %>

  </head>
  <body>
    <body>
        <%= render 'home/header'%>
        <div class="container" style="margin-top: 15px">
          <br>
          <% if notice %>
            <%= render 'layouts/alerts'%>
          <% end %>
          <%= yield %>
        </div>
        <%= render 'home/footer'%>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>